import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import Header from "@/components/layout/Header";


const inter = Inter({subsets:["latin"] });

export const metadata: Metadata = {
  title: "V-Store",
  description: "Generated by create Rahul",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-white text-black min-h-[125vh]`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
